name: cd-dev

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - "webapp/src/**"
      - "server/**"
      - "provision/**"

jobs:
  cd-webapp-dev:
    name: cd-webapp-dev
    permissions: # Explicitly define the permissions granted to the GITHUB_TOKEN for this job
      contents: write # Allows writing to the repository content
      checks: write # Allows creating and updating GitHub Checks (e.g., status checks for PRs)
      pull-requests: write # Allows interacting with pull requests (e.g., adding comments)
      id-token: write # Allows requesting OIDC (OpenID Connect) tokens for cloud provider authentication
      security-events: write # Allows submitting security events (e.g., vulnerability scans)
      actions: read # Allows reading metadata about other GitHub Actions
    uses: ./.github/workflows/cd-webapp.yml
    secrets: inherit # Passes all secrets available to this workflow to the called 'ci.yml' workflow
    with:
      env: "dev"
      terraform_env_dir: 'provision/environments/dev'
      autodeploy: false
