name: ci-webapp-dev

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      linter_for_committed_files_only:
        required: false
        default: false
        type: boolean
      run_server_jobs:
        required: false
        default: true
        type: boolean
      run_webapp_jobs:
        required: false
        default: true
        type: boolean

jobs:
  # CI for NextJS
  install-dependencies:
    name: install-dependencies
    if: inputs.run_webapp_jobs == true
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: './webapp/package-lock.json'
      - name: Install dependencies
        working-directory: webapp
        run: |
          npm ci --ignore-scripts

  linting:
    name: linting
    if: inputs.run_webapp_jobs == true
    needs: install-dependencies
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'webapp/package-lock.json'
      - name: Install dependencies
        working-directory: webapp
        run: |
          npm ci --ignore-scripts
      - name: Linter
        if: inputs.linter_for_committed_files_only == true
        uses: sibiraj-s/action-eslint@v3
        with:
          all-files: false
          working-directory: webapp
          extensions: ts,tsx
          ignore-patterns: |
            node_modules/
            .next/
            dist/
            dist/
            eslint.config.mjs
            .lintstagedrc.js
            .commitlintrc.js
            jest.config.ts
            .open-next/
            coverage/
          eslint-args: --config ./webapp/eslint.config.js webapp/

  test:
    name: test
    if: inputs.run_webapp_jobs == true
    needs: install-dependencies
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'webapp/package-lock.json'
      - name: Install dependencies
        working-directory: webapp
        run: |
          npm ci --ignore-scripts
      - name: Show unit test coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: webapp
          skip-step: install
          test-script: npx jest --ci --json --testLocationInResults --passWithNoTests --outputFile=report.json
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: build
    needs: install-dependencies
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'
          cache-dependency-path: 'webapp/package-lock.json'
      - name: Install dependencies
        working-directory: webapp
        run: npm ci --ignore-scripts

      - name: Build
        id: build
        working-directory: webapp
        run: |
          npm run build
          # npx open-next@3.1.3 build
